[server]
maxUploadSize = 1024

[theme]
base = "light"

# 브랜드 포인트 컬러
primaryColor = "#BE123C"

# 전체 앱 배경
backgroundColor = "#F4F5F7"

# 카드 / 입력창 / 사이드바 등의 배경
secondaryBackgroundColor = "#FFFFFF"

# 기본 텍스트
textColor = "#12151C"

# 폰트
font = "sans serif"
